// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppgabecfmbwfvqqkyqdb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwZ2FiZWNmbWJ3ZnZxcWt5cWRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MjcyNTgsImV4cCI6MjA1ODIwMzI1OH0.IjfGmqKHj6t_opPi60TAsMH12uApgN7l74VG_TbxA6A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);